backend:
  name: github
  repo: ua-tech-hub/tech-hub.in.ua
  branch: main
  open_authoring: true
locale: uk
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: "/images/uploads"
collections:
  - name: article
    label: Статті
    label_singular: Статтю
    folder: content/articles
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: articles/{{slug}}
    fields:
      - label: Автор
        name: author
        hint: GitHub логін автора статті
        widget: string
      - label: Заголовок
        name: title
        widget: string
      - label: Дата написання
        name: date
        widget: datetime
      - label: Теги
        name: tags
        widget: select
        multiple: true
        min: 1
        options:
          - HTML
          - CSS
          - JavaScript
          - TypeScript
          - Браузерні розширення
          - Electron
          - Vue
          - WordPress
          - Алгоритми
          - Чат-боти
          - Deno
          - Accessibility
      - label: Текст
        name: body
        widget: markdown
